export const CHAOS_SCENARIOS = [
  "REGIONAL_NETWORK_PARTITION",
  "DATABASE_CONNECTION_POOL_SATURATION",
  "ORCHESTRATOR_WORKER_DEADLOCK",
  "WEBHOOK_DELIVERY_FLOOD",
  "CASCADING_TOPOLOGY_FAILURE"
];
